package com.mscg;

import com.mscg.utils.InputUtils;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AntennaMapTest
{

	@Test
	void testCountAntiNodeLocations() throws Exception
	{
		final var antennaMap = AntennaMap.parseInput(InputUtils.readInput("""
				............
				........0...
				.....0......
				.......0....
				....0.......
				......A.....
				............
				............
				........A...
				.........A..
				............
				............"""));
		assertEquals(14, antennaMap.countAntiNodeLocations());
	}

	@Test
	void testCountAntiNodeLocationsWithHarmonics() throws Exception
	{
		final var antennaMap = AntennaMap.parseInput(InputUtils.readInput("""
				............
				........0...
				.....0......
				.......0....
				....0.......
				......A.....
				............
				............
				........A...
				.........A..
				............
				............"""));
		assertEquals(34, antennaMap.countAntiNodeLocationsWithHarmonics());
	}

}
